"""Argument validation for the offline executor.

The validator is the strict gate every tool call passes through, whether
the arguments were generated by `suggest_arguments` or supplied by the
multi-agent generator. Both paths are treated identically — there is no
"trusted" caller. This is the safety guarantee the assignment's §5.1
requires: arguments must reference real previous outputs, not
hallucinated placeholders.

Validation runs in three layers:

1. *Schema validation*: a Pydantic model is built dynamically from the
   endpoint's parameters (required vs optional, declared types). Missing
   required parameters and type mismatches surface as
   `MissingRequiredArgumentError` and `ArgumentTypeError`.
2. *Grounding validation*: for every parameter marked grounded by a
   transition pointing into this endpoint, the supplied value must
   appear in the session's issued-IDs index. Otherwise:
   `UngroundedArgumentError`.
3. *Strict-mode extras check*: optional. Refuses argument keys that
   don't appear in the endpoint schema at all. Off by default — some
   conversation patterns include speculative args that the executor
   should tolerate.

All errors carry enough metadata for the conversation log to render a
useful tool-error entry (which parameter, which value, what was
expected).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable

from pydantic import ValidationError, create_model

from kg_mle.executor.mocks import is_id_parameter
from kg_mle.executor.state import SessionState
from kg_mle.registry.models import Endpoint, Parameter
from kg_mle.sampler.constraints import Transition


# Map our internal types to Python types for dynamic Pydantic models.
_TYPE_MAP: dict[str, type] = {
    "string": str,
    "integer": int,
    "number": float,
    "boolean": bool,
    "array": list,
    "object": dict,
}


class ExecutorError(RuntimeError):
    """Base for typed executor failures.

    Each subclass carries a `to_log_entry()` returning the structured dict
    that goes into the conversation log's tool-error entry."""

    error_kind: str = "executor_error"

    def __init__(self, message: str, **details: Any) -> None:
        super().__init__(message)
        self.details = details

    def to_log_entry(self) -> dict[str, Any]:
        return {"kind": self.error_kind, "message": str(self), **self.details}


class MissingRequiredArgumentError(ExecutorError):
    error_kind = "missing_required_argument"


class ArgumentTypeError(ExecutorError):
    error_kind = "argument_type"


class UngroundedArgumentError(ExecutorError):
    error_kind = "ungrounded_argument"


class UnknownArgumentError(ExecutorError):
    error_kind = "unknown_argument"


@dataclass(frozen=True)
class ValidationContext:
    """Inputs the validator needs in addition to (endpoint, arguments)."""

    grounded_parameters: dict[str, str]
    """parameter_name -> source field name (or canonical name) that must
    have been issued by a previous step."""

    strict_extras: bool = False
    """If True, reject argument keys not declared on the endpoint."""


def grounded_parameters_for_endpoint(
    endpoint_id: str,
    incoming_transitions: Iterable[Transition],
) -> dict[str, str]:
    """Collect grounded-parameter -> source-field-name pairs.

    Used by the session when assembling a `ValidationContext` for a call.
    Only transitions whose advance_type is `grounded` contribute; the
    others either have no parameter binding (same_domain) or are
    explicitly opt-in (semantic_related).
    """
    grounded: dict[str, str] = {}
    for transition in incoming_transitions:
        if transition.target != endpoint_id:
            continue
        if transition.advance_type != "grounded":
            continue
        if transition.parameter is None:
            continue
        source = transition.source_field or transition.parameter
        grounded[transition.parameter] = source
    return grounded


def validate_arguments(
    endpoint: Endpoint,
    arguments: dict[str, Any],
    session_state: SessionState,
    context: ValidationContext,
) -> None:
    """Raise on any violation. Returns None on success.

    The caller (ExecutorSession) is responsible for recording the error
    in the conversation log before re-raising.
    """
    declared_params: dict[str, Parameter] = {param.name: param for param in endpoint.parameters}

    if context.strict_extras:
        unknown = set(arguments) - set(declared_params)
        if unknown:
            raise UnknownArgumentError(
                f"Unknown argument(s) {sorted(unknown)} for {endpoint.endpoint_id}.",
                endpoint=endpoint.endpoint_id,
                unknown=sorted(unknown),
            )

    _check_required_and_types(endpoint, declared_params, arguments)
    _check_grounding(endpoint, arguments, session_state, context)


def _check_required_and_types(
    endpoint: Endpoint,
    declared_params: dict[str, Parameter],
    arguments: dict[str, Any],
) -> None:
    """Use Pydantic to enforce required/type. Raises typed executor errors."""
    fields: dict[str, Any] = {}
    for name, param in declared_params.items():
        python_type = _TYPE_MAP.get(param.type, Any)
        default: Any = ... if param.required else None
        fields[name] = (python_type, default)

    DynamicModel = create_model(  # noqa: N806
        f"{endpoint.endpoint_id.replace('/', '__')}__Args",
        **fields,
    )

    try:
        DynamicModel(**arguments)
    except ValidationError as exc:
        first = exc.errors()[0]
        loc = first.get("loc", ("?",))
        param_name = str(loc[0])
        error_type = first.get("type", "")
        if "missing" in error_type:
            raise MissingRequiredArgumentError(
                f"Missing required argument {param_name!r} for {endpoint.endpoint_id}.",
                endpoint=endpoint.endpoint_id,
                parameter=param_name,
            ) from exc
        raise ArgumentTypeError(
            f"Argument {param_name!r} for {endpoint.endpoint_id} failed validation: {first.get('msg')}.",
            endpoint=endpoint.endpoint_id,
            parameter=param_name,
            expected_type=declared_params[param_name].type if param_name in declared_params else None,
            received=arguments.get(param_name),
        ) from exc


def _check_grounding(
    endpoint: Endpoint,
    arguments: dict[str, Any],
    session_state: SessionState,
    context: ValidationContext,
) -> None:
    """Every grounded parameter's value must appear in the session's
    issued-IDs index keyed by the source field name."""
    if not context.grounded_parameters:
        return

    for param_name, source_field in context.grounded_parameters.items():
        if param_name not in arguments:
            # If a grounded param was also marked required, the previous
            # check already raised. If not required, missing-and-grounded
            # is a no-op (nothing to check).
            continue

        value = arguments[param_name]
        # Strict grounding applies to all grounded parameters, ID or not.
        # The sampler's grounded transitions describe an output->input
        # promise; the value the assistant passes in must trace back to a
        # previous response.
        issued = session_state.issued_ids(source_field)
        if not issued and source_field != param_name:
            issued = session_state.issued_ids(param_name)
        if value not in issued:
            raise UngroundedArgumentError(
                f"Argument {param_name!r}={value!r} for {endpoint.endpoint_id} was not "
                f"issued by any previous tool call.",
                endpoint=endpoint.endpoint_id,
                parameter=param_name,
                source_field=source_field,
                value=value,
                expected_one_of=list(issued),
            )
